import rclpy
from airsim_interfaces.msg import VelCmd
from mavros_msgs.msg import AttitudeTarget, ExtendedState, PositionTarget
from nav_msgs.msg import Odometry
from rclpy.node import Node
from rclpy.qos import HistoryPolicy, QoSProfile, ReliabilityPolicy
from std_msgs.msg import Float32, String

from .vel_cmd_to_position_target import vel_cmd_to_position_target

NODE_NAME = 'uav_state_machine_node'

# Listen state input. Accepted values: GO_TO_TARGET, AVOID_OBSTACLE, LANDING,
# APPROACH (新增, 用于 YOLOE 识别到地面目标后的进近行为).
STATE_TOPIC = '/uav/state'

# Candidate control commands generated by upstream controllers.
GO_TO_TARGET_CMD_TOPIC = '/uav/control/go_to_target_cmd'
AVOID_OBSTACLE_CMD_TOPIC = '/uav/control/avoid_obstacle_cmd'
LANDING_CMD_TOPIC = '/uav/control/landing_cmd'
# 新增: 进近控制指令. 由上层规划节点 (例如 uav_with_rtl_node) 在收到
# YOLOE 识别结果后下发, 使无人机朝目标做受控进近. 与其他三个候选指令
# 完全并列, 状态机仅在 APPROACH 状态时转发.
APPROACH_CMD_TOPIC = '/uav/control/approach_cmd'

# yaw 设定话题 (rad, ROS ENU 世界系: yaw=0 朝东, +Z 逆时针).
# 默认所有状态都不下发 yaw, 由 PX4 自己锁当前 yaw. 上层节点可以在追踪
# 任务里发布 yaw_setpoint, 让机头持续指向目标 (例如让前向相机看到 AGV).
# 仅在 GO_TO_TARGET 状态下转发: AVOID/LANDING/APPROACH 都有自己的姿态
# 期望, 不该被巡航 yaw 干扰.
# Float32 含义: rad. 收到 NaN 等价于不下发 yaw.
YAW_SETPOINT_TOPIC = '/uav/control/yaw_setpoint'
# yaw_setpoint 多久没更新就视为失效 (s). 上层节点静默后状态机自动停下发
# yaw, 防止飞机一直按陈旧 yaw 转动.
YAW_SETPOINT_TIMEOUT_SEC = 0.5

# 输出话题. 整套链统一锚定 MAVROS ENU/FLU, 但分两条 setpoint 路径:
#   - 起飞期 (LANDED) 用 setpoint_raw/attitude 把飞机推离地面.
#   - 离地后用 setpoint_raw/local 走 PX4 BODY_NED velocity 控制环.
ATTITUDE_OUTPUT_TOPIC = '/mavros/setpoint_raw/attitude'
LOCAL_OUTPUT_TOPIC = '/mavros/setpoint_raw/local'

# MAVROS extended state, 用于判断 LANDED / IN_AIR.
EXTENDED_STATE_TOPIC = '/mavros/extended_state'
# Local odom, 用于读取相对地面的 z 高度 (ENU, 向上为正).
ODOM_TOPIC = '/mavros/local_position/odom'

# PX4 offboard requires a continuous setpoint stream. Publish at 20 Hz.
PUBLISH_PERIOD_SEC = 0.05

# 起飞 burst 推力. 略高于 PX4 默认 hover 推力 0.5 即可让飞机短暂破地.
# 不依赖任何位置估计, 也不指定世界坐标系绝对方向.
TAKEOFF_THRUST = 0.7

# 起飞完成的相对高度阈值 (m). 飞机相对起飞地面 z 抬升 >= 此值后才切到
# velocity 控制环. 不依赖世界坐标系绝对位置, 只依赖 EKF 出来的相对 z,
# 这部分主要靠气压计 + IMU 融合, 对 GPS 米级误差不敏感.
TAKEOFF_RELEASE_HEIGHT_M = 2.0

# 起飞 burst 最少持续多长时间 (s) 才允许判定离地. 防止 OFFBOARD 切换
# 瞬间 EKF z 抖动 / landed_state 抖动直接触发锁存, 让飞机还没起来就被
# 切到 velocity 控制环, 然后掉回去.
TAKEOFF_MIN_BURST_SECONDS = 3.0

# MAVLink landed_state == 2 表示 IN_AIR.
LANDED_STATE_IN_AIR = 2

STATE_GO_TO_TARGET = 'GO_TO_TARGET'
STATE_AVOID_OBSTACLE = 'AVOID_OBSTACLE'
STATE_LANDING = 'LANDING'
# 新增状态: 巡航期间 YOLOE 识别到目标 (例如返航途中识别到地面 AGV) 后,
# 上层节点会发布该状态以打断当前巡航, 让状态机转发进近指令而非巡航指令.
# 不修改既有 GO_TO_TARGET / AVOID_OBSTACLE / LANDING 的语义.
STATE_APPROACH = 'APPROACH'

# MAVLink landed_state 枚举. 1 = ON_GROUND.
LANDED_STATE_ON_GROUND = 1


def _is_zero_cmd(cmd: VelCmd) -> bool:
    t = cmd.twist
    return (
        abs(t.linear.x) < 1e-3
        and abs(t.linear.y) < 1e-3
        and abs(t.linear.z) < 1e-3
        and abs(t.angular.x) < 1e-3
        and abs(t.angular.y) < 1e-3
        and abs(t.angular.z) < 1e-3
    )


def _hover_cmd_like(reference: VelCmd | None) -> VelCmd:
    # In AVOID, keep altitude fixed and stop all horizontal motion. We do not
    # reuse the cruise controller's z command here, otherwise the UAV can keep
    # climbing/descending while trying to dodge obstacles.
    cmd = VelCmd()
    return cmd


class UavStateMachineNode(Node):
    def __init__(self):
        super().__init__(NODE_NAME)

        # MAVROS 大部分 status / sensor 话题用 BEST_EFFORT, 否则订阅看不到消息.
        be_qos = QoSProfile(
            reliability=ReliabilityPolicy.BEST_EFFORT,
            history=HistoryPolicy.KEEP_LAST,
            depth=10,
        )

        # High-level state decides which candidate VelCmd should be active.
        self.current_state = STATE_GO_TO_TARGET

        # Cache the latest candidate command from each upstream controller.
        self.go_to_target_cmd: VelCmd | None = None
        self.avoid_obstacle_cmd: VelCmd | None = None
        self.landing_cmd: VelCmd | None = None
        self.approach_cmd: VelCmd | None = None

        # 上游 yaw_setpoint 缓存. None 表示未启用 / 已超时, 此时
        # _publish_velocity_setpoint 不会向 PX4 下发 yaw, 由 PX4 自己锁当前 yaw.
        # 仅在 GO_TO_TARGET 状态下生效.
        self._yaw_setpoint_rad: float | None = None
        self._yaw_setpoint_stamp_ns: int | None = None

        # Cache the latest selected command. A timer republishes this command at
        # a fixed rate so PX4 offboard keeps receiving setpoints even when the
        # upstream controller is momentarily quiet.
        self.active_cmd = VelCmd()

        # 起飞 / 离地相关. 默认假设在地面, 等 extended_state 真正报上来再更新.
        # has_left_ground 一旦置 True 就单向锁存, 保证后续 landed_state 抖动
        # 不会让我们跳回 takeoff burst, 否则会触发 OFFBOARD 模式失败保护.
        # ground_z 在第一次收到 odom 时记录起飞地面 z (ENU, 向上为正), 切换
        # 阈值是相对于这个 z 的高度差, 不使用世界坐标系绝对位置.
        # takeoff_burst_start_ns 在第一次发出 takeoff burst 时记录, 用来
        # 判断 burst 是否已经持续了足够时间, 避免 EKF / landed_state 在
        # OFFBOARD 切换瞬间抖动直接触发锁存.
        self.is_on_ground = True
        self.is_in_air = False
        self.has_left_ground = False
        self.ground_z: float | None = None
        self.current_z: float | None = None
        self.takeoff_burst_start_ns: int | None = None

        self.state_subscription = self.create_subscription(
            String,
            STATE_TOPIC,
            self.state_callback,
            10,
        )
        self.go_to_target_subscription = self.create_subscription(
            VelCmd,
            GO_TO_TARGET_CMD_TOPIC,
            self.go_to_target_cmd_callback,
            10,
        )
        self.avoid_obstacle_subscription = self.create_subscription(
            VelCmd,
            AVOID_OBSTACLE_CMD_TOPIC,
            self.avoid_obstacle_cmd_callback,
            10,
        )
        self.landing_subscription = self.create_subscription(
            VelCmd,
            LANDING_CMD_TOPIC,
            self.landing_cmd_callback,
            10,
        )
        # 新增订阅: 进近候选指令.
        self.approach_subscription = self.create_subscription(
            VelCmd,
            APPROACH_CMD_TOPIC,
            self.approach_cmd_callback,
            10,
        )
        # 新增订阅: yaw_setpoint (rad, ENU 世界系). 仅 GO_TO_TARGET 下生效.
        self.yaw_setpoint_subscription = self.create_subscription(
            Float32,
            YAW_SETPOINT_TOPIC,
            self.yaw_setpoint_callback,
            10,
        )
        # 订阅 extended_state, 用于判断起飞是否完成.
        self.extended_state_subscription = self.create_subscription(
            ExtendedState,
            EXTENDED_STATE_TOPIC,
            self.extended_state_callback,
            be_qos,
        )
        # 订阅 local_position/odom, 拿相对地面 z 用于切换条件 (不依赖
        # 世界坐标系绝对位置).
        self.odom_subscription = self.create_subscription(
            Odometry,
            ODOM_TOPIC,
            self.odom_callback,
            be_qos,
        )

        # 两个 publisher: 起飞期发 attitude + thrust, 离地后发 BODY_NED velocity.
        self.attitude_pub = self.create_publisher(
            AttitudeTarget, ATTITUDE_OUTPUT_TOPIC, 10
        )
        self.local_pub = self.create_publisher(
            PositionTarget, LOCAL_OUTPUT_TOPIC, 10
        )

        # Keep publishing the latest selected command for PX4 offboard.
        self.publish_timer = self.create_timer(
            PUBLISH_PERIOD_SEC, self.publish_active_cmd
        )

        self.get_logger().info(
            f'Listening state={STATE_TOPIC}, '
            f'candidates={{go_to_target, avoid_obstacle, landing, approach}}; '
            f'takeoff burst -> {ATTITUDE_OUTPUT_TOPIC}, '
            f'cruise velocity -> {LOCAL_OUTPUT_TOPIC} '
            f'at {1.0 / PUBLISH_PERIOD_SEC:.1f}Hz'
        )

    def extended_state_callback(self, msg: ExtendedState):
        # landed_state: 0=UNDEFINED, 1=ON_GROUND, 2=IN_AIR, 3=TAKEOFF, 4=LANDING.
        # 这里同时维护两个标志, 起飞条件需要 landed_state 真正变成 IN_AIR.
        self.is_on_ground = (msg.landed_state == LANDED_STATE_ON_GROUND)
        self.is_in_air = (msg.landed_state == LANDED_STATE_IN_AIR)

    def odom_callback(self, msg: Odometry):
        z = float(msg.pose.pose.position.z)
        self.current_z = z
        # 第一次收到 odom 时记录地面 z (此时飞机还在地面). 后续整个流程
        # 都用 (current_z - ground_z) 作为相对高度判据.
        if self.ground_z is None:
            self.ground_z = z
            return
        # 起飞 burst 阶段持续抬升, 只有同时满足下面三件事才单向锁存:
        #   1) burst 已经持续 >= TAKEOFF_MIN_BURST_SECONDS;
        #   2) mavros 报告 landed_state == IN_AIR;
        #   3) 相对地面 z 抬升 >= TAKEOFF_RELEASE_HEIGHT_M.
        # 这三道门可以挡住 OFFBOARD 切换瞬间 EKF z 抖动 / landed_state
        # 抖动单独触发的伪锁存, 不依赖任何世界坐标系绝对位置.
        if self.has_left_ground:
            return
        if self.takeoff_burst_start_ns is None:
            return
        burst_dt = (
            self.get_clock().now().nanoseconds - self.takeoff_burst_start_ns
        ) * 1e-9
        if burst_dt < TAKEOFF_MIN_BURST_SECONDS:
            return
        if not self.is_in_air:
            return
        if (z - self.ground_z) < TAKEOFF_RELEASE_HEIGHT_M:
            return
        self.has_left_ground = True
        self.get_logger().info(
            f"left ground: rel_z={z - self.ground_z:.2f}m, "
            f"burst={burst_dt:.2f}s, in_air={self.is_in_air}, "
            f"switch to BODY_NED velocity setpoints",
        )

    def _set_active_cmd(self, cmd: VelCmd | None):
        # All state transitions and candidate-command callbacks end up here. We
        # store the currently active VelCmd, and the timer below handles the
        # continuous setpoint publishing required by PX4 offboard mode.
        self.active_cmd = cmd if cmd is not None else VelCmd()

    def publish_active_cmd(self):
        # 起飞前: 持续发 takeoff burst, 不依赖任何位置估计.
        # 起飞后: 单向锁存到 BODY_NED velocity-only setpoint.
        #
        # 旧实现为了防止“刚离地就切 velocity-only 掉回去”，把整个纯垂直爬升
        # 阶段都继续走 burst。副作用是飞机在 UAV_ASCEND 期间一直吃固定推力
        # TAKEOFF_THRUST，不再受上游 vz=+3 和后续高度控制约束，容易一路冲到
        # 远高于 10m 的高度。现在 burst 只负责破地；一旦满足离地锁存条件，
        # 就立刻切回 velocity-only，让 PX4 按期望 vz 控制爬升。
        if not self.has_left_ground:
            self._publish_takeoff_burst()
        else:
            self._publish_velocity_setpoint()

    def _publish_takeoff_burst(self):
        # 起飞 burst: 不指定世界坐标系下的绝对位置, 只发 "保持当前姿态 +
        # 零角速率 + 略高于悬停推力", 让 PX4 内部直接驱动电机把飞机推离
        # 地面. type_mask = IGNORE_ATTITUDE 意为 PX4 不依据 orientation
        # 改变姿态, 只按 body_rate + thrust 工作, 保持当前 yaw/roll/pitch.
        if self.takeoff_burst_start_ns is None:
            self.takeoff_burst_start_ns = self.get_clock().now().nanoseconds
        msg = AttitudeTarget()
        msg.header.stamp = self.get_clock().now().to_msg()
        msg.type_mask = AttitudeTarget.IGNORE_ATTITUDE
        msg.body_rate.x = 0.0
        msg.body_rate.y = 0.0
        msg.body_rate.z = 0.0
        msg.thrust = TAKEOFF_THRUST
        self.attitude_pub.publish(msg)
        burst_dt = (
            self.get_clock().now().nanoseconds - self.takeoff_burst_start_ns
        ) * 1e-9
        rel_z = (
            (self.current_z - self.ground_z)
            if (self.current_z is not None and self.ground_z is not None)
            else 0.0
        )
        self.get_logger().info(
            f"takeoff burst: thrust={TAKEOFF_THRUST:.2f} "
            f"burst={burst_dt:.2f}s rel_z={rel_z:+.2f}m "
            f"on_ground={self.is_on_ground} in_air={self.is_in_air}",
            throttle_duration_sec=1.0,
        )

    def _publish_velocity_setpoint(self):
        # 离地后: 用 PX4 BODY_NED velocity 控制环跟踪上游 cmd, 不再自写姿态.
        # 仅 GO_TO_TARGET 状态下顺带下发 yaw 设定, 让机头持续指向目标.
        yaw_setpoint = self._current_yaw_setpoint()
        msg = vel_cmd_to_position_target(
            self.active_cmd, self.get_clock().now().to_msg(), yaw_setpoint=yaw_setpoint,
        )
        self.local_pub.publish(msg)
        yaw_str = f"{yaw_setpoint:+.2f}rad" if yaw_setpoint is not None else "off"
        self.get_logger().info(
            f"cmd vx={self.active_cmd.twist.linear.x:+.2f} "
            f"vy={self.active_cmd.twist.linear.y:+.2f} "
            f"vz={self.active_cmd.twist.linear.z:+.2f} | "
            f"out vx={msg.velocity.x:+.2f} "
            f"vy={msg.velocity.y:+.2f} "
            f"vz={msg.velocity.z:+.2f} yaw={yaw_str}",
            throttle_duration_sec=1.0,
        )

    def state_callback(self, msg: String):
        state = msg.data.strip().upper()
        if state not in (
            STATE_GO_TO_TARGET,
            STATE_AVOID_OBSTACLE,
            STATE_LANDING,
            STATE_APPROACH,
        ):
            self.get_logger().warn(f'Ignoring unknown state: {state}')
            return

        if state != self.current_state:
            self.get_logger().info(f'State changed: {self.current_state} -> {state}')
            self.current_state = state

        self.publish_selected_cmd()

    def go_to_target_cmd_callback(self, msg: VelCmd):
        # Always cache the latest cruise command. Forward only when active so
        # the AVOID/LANDING states never get pushed by the direct-target speed.
        self.go_to_target_cmd = msg
        if self.current_state == STATE_GO_TO_TARGET:
            self._set_active_cmd(msg)

    def avoid_obstacle_cmd_callback(self, msg: VelCmd):
        self.avoid_obstacle_cmd = msg
        if self.current_state == STATE_AVOID_OBSTACLE:
            self._set_active_cmd(self._avoid_output(msg))

    def landing_cmd_callback(self, msg: VelCmd):
        self.landing_cmd = msg
        if self.current_state == STATE_LANDING:
            self._set_active_cmd(msg)

    def approach_cmd_callback(self, msg: VelCmd):
        # 进近指令仅在 APPROACH 状态下被转发, 否则只缓存. 与其它三个回调
        # 一一对应, 不影响巡航 / 避障 / 降落的任何分支.
        self.approach_cmd = msg
        if self.current_state == STATE_APPROACH:
            self._set_active_cmd(msg)

    def yaw_setpoint_callback(self, msg: Float32):
        # 上游持续下发 yaw 设定 (rad, ENU). 仅 GO_TO_TARGET 状态下生效;
        # 缓存到本地, _publish_velocity_setpoint 真正下发时再做新鲜度判断.
        # 收到 NaN/Inf 视为停止 yaw 控制.
        value = float(msg.data)
        if value != value or value in (float("inf"), -float("inf")):  # NaN/Inf
            self._yaw_setpoint_rad = None
            self._yaw_setpoint_stamp_ns = None
            return
        self._yaw_setpoint_rad = value
        self._yaw_setpoint_stamp_ns = self.get_clock().now().nanoseconds

    def _current_yaw_setpoint(self) -> float | None:
        # 仅在 GO_TO_TARGET 状态下使用上游 yaw, 其它状态保持现有 IGNORE_YAW.
        if self.current_state != STATE_GO_TO_TARGET:
            return None
        if self._yaw_setpoint_rad is None or self._yaw_setpoint_stamp_ns is None:
            return None
        age_sec = (self.get_clock().now().nanoseconds - self._yaw_setpoint_stamp_ns) * 1e-9
        if age_sec > YAW_SETPOINT_TIMEOUT_SEC:
            return None
        return self._yaw_setpoint_rad

    def publish_selected_cmd(self):
        # On state switch immediately publish a command consistent with the new
        # state, using cached commands when fresh ones are not available yet.
        if self.current_state == STATE_GO_TO_TARGET:
            self._set_active_cmd(self.go_to_target_cmd)
        elif self.current_state == STATE_AVOID_OBSTACLE:
            self._set_active_cmd(self._avoid_output(self.avoid_obstacle_cmd))
        elif self.current_state == STATE_APPROACH:
            # 切到 APPROACH: 优先用缓存的进近指令; 没有就发零速悬停,
            # 不退回到 cruise, 避免把无人机继续推往原巡航方向.
            self._set_active_cmd(self.approach_cmd)
        else:  # STATE_LANDING
            # No landing command yet: stay still rather than fall back to cruise
            # speed, which would carry the UAV past the target.
            self._set_active_cmd(self.landing_cmd)

    def _avoid_output(self, avoid_cmd: VelCmd | None) -> VelCmd:
        # AVOID state must never fall back to the cruise command, otherwise the
        # UAV would keep being pushed straight toward the obstacle whenever DWB
        # produces an empty plan. If avoidance is missing or zero, hold height.
        if avoid_cmd is None or _is_zero_cmd(avoid_cmd):
            return _hover_cmd_like(self.go_to_target_cmd)
        return avoid_cmd


def main(args=None):
    rclpy.init(args=args)
    node = UavStateMachineNode()

    try:
        rclpy.spin(node)
    finally:
        node.destroy_node()
        rclpy.shutdown()


if __name__ == '__main__':
    main()
